version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    reviewers:
      - 'VKCOM/vk-sec'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'VKCOM/vk-sec'
